name = "telegram-bot-worker"
type = "javascript"
account_id = "akbarifar@gmail.com"
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "telegram-bot-worker"
route = "https://your-domain.com/*"
